// <auto-generated />
using System;
using InlandMarinaData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InlandMarinaData.Migrations
{
    [DbContext(typeof(InlandMarinaContext))]
    [Migration("20240724163237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InlandMarinaData.Dock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("ElectricalService")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("WaterService")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Dock");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ElectricalService = true,
                            Name = "Dock A",
                            WaterService = true
                        },
                        new
                        {
                            ID = 2,
                            ElectricalService = false,
                            Name = "Dock B",
                            WaterService = true
                        },
                        new
                        {
                            ID = 3,
                            ElectricalService = true,
                            Name = "Dock C",
                            WaterService = false
                        });
                });

            modelBuilder.Entity("InlandMarinaData.Lease", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SlipID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("SlipID");

                    b.ToTable("Lease");
                });

            modelBuilder.Entity("InlandMarinaData.Slip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DockID")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DockID");

                    b.ToTable("Slip");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DockID = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 2,
                            DockID = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 3,
                            DockID = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 4,
                            DockID = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 5,
                            DockID = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 6,
                            DockID = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 7,
                            DockID = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 8,
                            DockID = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 9,
                            DockID = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 10,
                            DockID = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 11,
                            DockID = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 12,
                            DockID = 1,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 13,
                            DockID = 1,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 14,
                            DockID = 1,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 15,
                            DockID = 1,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 16,
                            DockID = 1,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 17,
                            DockID = 1,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 18,
                            DockID = 1,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 19,
                            DockID = 1,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 20,
                            DockID = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 21,
                            DockID = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 22,
                            DockID = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 23,
                            DockID = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 24,
                            DockID = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 25,
                            DockID = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 26,
                            DockID = 1,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 27,
                            DockID = 1,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 28,
                            DockID = 1,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 29,
                            DockID = 1,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 30,
                            DockID = 1,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 31,
                            DockID = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 32,
                            DockID = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 33,
                            DockID = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 34,
                            DockID = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 35,
                            DockID = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 36,
                            DockID = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 37,
                            DockID = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 38,
                            DockID = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 39,
                            DockID = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 40,
                            DockID = 2,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 41,
                            DockID = 2,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 42,
                            DockID = 2,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 43,
                            DockID = 2,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 44,
                            DockID = 2,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 45,
                            DockID = 2,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 46,
                            DockID = 2,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 47,
                            DockID = 2,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 48,
                            DockID = 2,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 49,
                            DockID = 2,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 50,
                            DockID = 2,
                            Length = 30,
                            Width = 8
                        },
                        new
                        {
                            ID = 51,
                            DockID = 2,
                            Length = 30,
                            Width = 8
                        },
                        new
                        {
                            ID = 52,
                            DockID = 2,
                            Length = 30,
                            Width = 8
                        },
                        new
                        {
                            ID = 53,
                            DockID = 2,
                            Length = 30,
                            Width = 8
                        },
                        new
                        {
                            ID = 54,
                            DockID = 2,
                            Length = 30,
                            Width = 8
                        },
                        new
                        {
                            ID = 55,
                            DockID = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 56,
                            DockID = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 57,
                            DockID = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 58,
                            DockID = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 59,
                            DockID = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 60,
                            DockID = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 61,
                            DockID = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 62,
                            DockID = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 63,
                            DockID = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 64,
                            DockID = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 65,
                            DockID = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 66,
                            DockID = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 67,
                            DockID = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 68,
                            DockID = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 69,
                            DockID = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 70,
                            DockID = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 71,
                            DockID = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 72,
                            DockID = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 73,
                            DockID = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 74,
                            DockID = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 75,
                            DockID = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 76,
                            DockID = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 77,
                            DockID = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 78,
                            DockID = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 79,
                            DockID = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 80,
                            DockID = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 81,
                            DockID = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 82,
                            DockID = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 83,
                            DockID = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 84,
                            DockID = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 85,
                            DockID = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 86,
                            DockID = 3,
                            Length = 32,
                            Width = 12
                        },
                        new
                        {
                            ID = 87,
                            DockID = 3,
                            Length = 32,
                            Width = 12
                        },
                        new
                        {
                            ID = 88,
                            DockID = 3,
                            Length = 32,
                            Width = 12
                        },
                        new
                        {
                            ID = 89,
                            DockID = 3,
                            Length = 32,
                            Width = 12
                        },
                        new
                        {
                            ID = 90,
                            DockID = 3,
                            Length = 32,
                            Width = 12
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InlandMarinaData.Customer", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.ToTable("User");
                });

            modelBuilder.Entity("InlandMarinaData.Lease", b =>
                {
                    b.HasOne("InlandMarinaData.Customer", "Customer")
                        .WithMany("Leases")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InlandMarinaData.Slip", "Slip")
                        .WithMany("Leases")
                        .HasForeignKey("SlipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Slip");
                });

            modelBuilder.Entity("InlandMarinaData.Slip", b =>
                {
                    b.HasOne("InlandMarinaData.Dock", "Dock")
                        .WithMany("Slips")
                        .HasForeignKey("DockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dock");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InlandMarinaData.Customer", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("InlandMarinaData.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InlandMarinaData.Dock", b =>
                {
                    b.Navigation("Slips");
                });

            modelBuilder.Entity("InlandMarinaData.Slip", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("InlandMarinaData.Customer", b =>
                {
                    b.Navigation("Leases");
                });
#pragma warning restore 612, 618
        }
    }
}
